apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    ############################################################
    # IRSA annotation
    # Links this service account to the AWS IAM role
    # Pods using this SA automatically get AWS credentials
    # without any hardcoded keys
    ############################################################
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}