# Required by nginx, even if no event tuning is needed
# written in nginx configuration language.
events {} 
# mandatory block in nginx, nginx won’t start without an events block

http {
  server {
    # nginx listens on port 8000
    # This is the only exposed port from the container
    listen 8000;

    # Serve static content for root URL (/)
    # Example: nginx landing page or health info
    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    # Reverse proxy for health checks
    # Forwards requests to FastAPI running on uvicorn
    location /health {
      proxy_pass http://127.0.0.1:8001;
    }

    # Reverse proxy for ECG API
    # nginx does not handle business logic
    # It forwards requests to FastAPI
    location /ecg {
      proxy_pass http://127.0.0.1:8001;
    }
  }
}
