############################################################
# ARGOCD APPLICATION: EXTERNAL-SECRETS
# Multi-source: chart from its upstream Helm repo, values
# from our own repo, same pattern as the other two
############################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.7.0
      helm:
        valueFiles:
          - $values/helm/external-secrets/values.yaml

    - repoURL: https://github.com/ShivamPanchbhai/AWS-EKS-Platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true