############################################################
# EXTERNAL SECRET
# Tells ESO which secret to fetch from SSM
# and what Kubernetes Secret to create from it
############################################################
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  # How often ESO syncs the secret from SSM
  refreshInterval: 1h

  secretStoreRef:
    # References the SecretStore defined above
    name: aws-ssm-store
    kind: SecretStore

  target:
    # Name of the Kubernetes Secret ESO will create
    name: alertmanager-smtp-secret
    creationPolicy: Owner

  data:
    - secretKey: smtp_password
      remoteRef:
        # Path in SSM Parameter Store
        key: /monitoring/smtp-password