############################################################
# SECRET STORE
# Tells ESO where to fetch secrets from
# Points to AWS SSM Parameter Store in ap-south-1
# Uses Pod Identity for AWS credentials -- no hardcoded keys
############################################################
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
  # Scoped to monitoring namespace where Alertmanager runs
  namespace: monitoring
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            # ESO service account linked to IAM role via Pod Identity
            name: external-secrets