name: AWS OIDC Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::306991549269:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity
